// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "Markdown",
    platforms: [.macOS(.v14)],
    products: [
        .executable(name: "Markdown", targets: ["Markdown"]),
        .library(name: "MarkdownKit", targets: ["MarkdownKit"]),
    ],
    targets: [
        // Generated by scripts/build-core.sh (gitignored).
        .binaryTarget(
            name: "MarkdownCoreFFI",
            path: "Frameworks/MarkdownCoreFFI.xcframework"
        ),
        // Generated UniFFI Swift bindings; imports the `markdown_ffiFFI` clang module.
        .target(
            name: "MarkdownCore",
            dependencies: ["MarkdownCoreFFI"]
        ),
        .target(
            name: "MarkdownKit",
            dependencies: ["MarkdownCore"]
        ),
        .executableTarget(
            name: "Markdown",
            dependencies: ["MarkdownKit"]
        ),
        .testTarget(
            name: "MarkdownKitTests",
            dependencies: ["MarkdownKit", "MarkdownCore"]
        ),
    ],
    swiftLanguageModes: [.v5]
)
